const DEFAULT_SUPABASE_URL = 'https://zmykmhmdqbslztqeecel.supabase.co';
const DEFAULT_SUPABASE_ANON_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpteWttaG1kcWJzbHp0cWVlY2VsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2NDM0MjksImV4cCI6MjA3NjIxOTQyOX0.Q802aBlB2VRua9pqJ7RzCqmqwwuA2BKKPG7XL0d9U9E';

export const SUPABASE_URL =
  process.env.NEXT_PUBLIC_SUPABASE_URL ?? DEFAULT_SUPABASE_URL;

export const SUPABASE_ANON_KEY =
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? DEFAULT_SUPABASE_ANON_KEY;

export const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
